### PR TITLE
More fixes and enhancements

### PR DESCRIPTION
**Pull request by josch1710**
Some more fixes and enhancements:

- Split number parsing to be able to parse the arc command parameters.
- Consume the arc command and set the correct end point.
- Handle to correctly set the start point of short hand bezier commands.
- Handle a tag closed by "/>"

### CODE REVIEW

**Comment by savetz** [comment]
Great additions. And thank you for making the world's most-nested IF-THEN yet another level deeper.

**Comment by josch1710** [comment]
I write that on my gravestone ;-)

**Comment by josch1710** [comment]
BTW, I couldn't find anything in the SVG spec for the notion, that negative coordinates imply relative coordinates. How did that come about?

**Comment by savetz** [comment]
You're right: re-reading the spec at https://www.w3.org/TR/SVGTiny12/paths.html#PathDataLinetoCommands I don't see that specified. Maybe it was an incorrect assumption on my part. Or, I found SVG files that used a negative after a capital H or V and assumed. I don't remember now.

**Comment by savetz** [comment]
In the "Bugs and things" section of the README, is it safe to remove "I kind of wanted to add the "a"rc path command..." and "the program prints the image upside down on the plotter"?

Have you tested the Atari800MacX emulator's plotter emulation since fixing the plotter output?

**Comment by josch1710** [comment]
Actually, I haven't implemented arc yet, other than consuming it and setting the end point as next point, but I'm planning to. 
The upside down problem was tested on an actual 1020 ;-), so that remark can be deleted.
Concerning relative and negative coordinates, I already removed that, but left the comments.

There are a few features, I'm thinking about, like:
- Line clipping, e.g. with Cohen–Sutherland algorithm. With clipping, lines crossing the view window would be drawn.
- Automatic scaling via the width/height resp. viewBox parameters in the svg tag.
- Coloring the plotting output according to the color infos in the draw commands. Pens could be selected to be the nearest one to specified color, e.g. dark orange becomes red and so on.
- Since text is possible in graphics mode on a 1020, we could add this, too.

What do you think?

**Comment by savetz** [comment]
What do I think? Go for it!

**Comment by josch1710** [comment]
Ok, just wanted to be sure.

I created some issues to track features.

**Pull request merged**
